### ISSUE TITLE
Download and execute payload 

### ISSUE THREAD

**Issue by b3mb4m** [trustedsec/unicorn#10]
Metasploit meterpreter too limited.Download&exec payload would be great, i can implement to unicorn soon if nobody already done it.

https://github.com/rapid7/metasploit-framework/blob/master/modules/payloads/singles/windows/download_exec.rb

**Comment by adelashraf** [comment]
ok I will try soon

**Comment by b3mb4m** [comment]
I look forward to! Thank you :)

**Comment by adelashraf** [comment]
you're welcome :D

**Comment by trustedsec** [comment]
I've added this to version 2.3, download_exec is now supported and updated. Thanks for the recommendation!
