### ISSUE TITLE
what are you trying to do?

### ISSUE THREAD

**Issue by CyberTheReape** [trustedsec/unicorn#105]
many people used the unicorn program and the computer's cpu broke down??? Who is using this program will break the processor.
Now a friend of mine again texted me.
The computer freezes after using the unicorn program.(cpu %99)
my friend formatted the computer.
but the same problem still continues.
he also cannot install virus program on computer after throwing formatting.
2 of my friends had told me before.
they had the same problem. when we heard the same problem today, we started to doubt you.
we decided to delete unicorn video on our youtube channel.I will suggest all hack sites not to use the unicorn program..

**Comment by trustedsec** [comment]
Unicorn is open source.

**Comment by the-exodus** [comment]
Oh couldn't you have left this open? I'm all out of Monty Python dvds :(

**Comment by NullArray** [comment]
I know this is an old ticket but here is some advice for the ages @Phoenix1112 

If you can't read the source code, don't use the tool. I am 100% sure Unicorn devs have done nothing malicious here, but someone else might have taken the code and altered it.

So like i said if you can't read the code, maybe not use the tool, eh?
