### ISSUE TITLE
Again patched by windows.

### ISSUE THREAD

**Issue by dsx12** [trustedsec/unicorn#106]
They're detecting again... (heads up)

**Comment by dsx12** [comment]
I believe they're flagging the first line of code as malicious now:

this script contians malicious instructions etc...

"powershell /w 1 /C "s''v ou -;s''v WW e''c;s''v zTO"

**Comment by trustedsec** [comment]
I pushed an update already - it wasn't on that it was on the CreateThread function, should last a little longer this time

**Comment by dsx12** [comment]
Hopefully lol they're onto your script big time.

**Comment by dsx12** [comment]
How long you think until they fully patch the method?

**Comment by brunoaduarte** [comment]
Still detected by Win10

> TrojanDropper:PowerShell/Ploty.gen!A

**Comment by brunoaduarte** [comment]
Still detected by Win10

![image](https://user-images.githubusercontent.com/5354345/53387630-78f0b880-3966-11e9-88d1-ce8f7fb176c7.png)

**Comment by brunoaduarte** [comment]
@dsx12 hey man, are you able to customize the payload so it goes undetected by MS?
