### ISSUE TITLE
A small question

### ISSUE THREAD

**Issue by pple7000** [trustedsec/unicorn#109]
Can this tool run with meterpreter?
Because I don't find any options that can set lhost and lport 

I want to open moniter on metasploit and catch the respond of payload

**Comment by lonelycount** [comment]
To my knowleague the thing was designed to run payload generated by msfvenom, thus by default it has to run on msfconsole, the options to set lhost and lport is right there when u use it. 
Ex: python unicorn.py -p your_payload_type 192.168.1.133 4444 etc.

**Comment by tygaking009** [comment]
If you are having issues then go watch some video tutorials on youtube Brother

**Comment by pple7000** [comment]
Thanks!!!
