### ISSUE TITLE
Please help answer my question sir

### ISSUE THREAD

**Issue by tygaking009** [trustedsec/unicorn#113]
I would like to ask does unicorn work only on 64 bit machines??? Windows 7/8/10?

**Comment by tygaking009** [comment]
I created a payload and ran it on a 32 bit system and i did not get a session. -- please how can i fix this?

**Comment by dsx12** [comment]
Likely it is patched, run in cmd "powershell attackfile.ps1"

You will likely get a output saying
"
+ ~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent
"
if so the script is now blocked by antivirus software.

**Comment by dsx12** [comment]
If you play with the code you may be able to bypass, though..

**Comment by tygaking009** [comment]
Please what other scripts would you recommend?

**Comment by trustedsec** [comment]
Microsoft releases updates since this is a highly popular and public tool. I make changes here and there which are trivial, but take time to do.
