### ISSUE TITLE
Macro runtime error

### ISSUE THREAD

**Issue by moaeddy** [trustedsec/unicorn#120]
there is runtime error in Macro code image attached
![macro-error](https://user-images.githubusercontent.com/7292467/55939684-3d970a00-5bf3-11e9-902c-ab3dfbdc43f9.jpg)

**Comment by trustedsec** [comment]
Hmm, I'm unable to reproduce this one. I'm using Windows 10 and on the latest version of Office.. Are you using an older version of Unicorn? My first line looks like this:

KQMrdppz = " /w 1 /C ""sv AZu -;sv Pd ec;sv O"

**Comment by trustedsec** [comment]
This is fixed in the latest release
