### ISSUE TITLE
PLease trustedsec 

### ISSUE THREAD

**Issue by tygaking009** [trustedsec/unicorn#127]
First of all thank you for this amazing tool,You did a great job but i would like to ask if there is a way to make the macro codes generated from unicorn tool more Fud Because i cant seem to bypass any Antivirus with it

**Comment by trustedsec** [comment]
It's always a cat and mouse game, we make updates as much as we can but usually with anything public, new signatures are written for it. Recommendation would be to customize it to your desire.
