### ISSUE TITLE
No connection

### ISSUE THREAD

**Issue by Bry-fi** [trustedsec/unicorn#13]
Everytime I execute a payload on a windows machine (running 8) none of the attacks give me back a connection. I run the Social Engineering Toolkit version of the powershell attack and it works fine so it is not my computer.

**Comment by trustedsec** [comment]
Running Windows 8, Windows 10, Server 2008, Server 2012 and the shells are all spawned and connections work fine on both internal/external IP addresses. 

Unable to reproduce.
