### ISSUE TITLE
Powershell Payload detected and by windows defender

### ISSUE THREAD

**Issue by BustedSec** [trustedsec/unicorn#130]
running the script results in the following error message from powershell
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
This script contains malicious content and has been blocked by your antivirus software.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : ScriptContainedMaliciousContent

The test vm is running windows defender out of the box with defender turned off, yet it is still able to block execution somehow.

**Comment by trustedsec** [comment]
This happens quite frequently due to the popularity of Unicorn. As we have time we make updates usually once or twice a month and push new versions out. You can easily modify the source though as the AMSI detections are usually very trivial and only take a few minutes.
