### ISSUE TITLE
Not able to load OSX payload in the macro command

### ISSUE THREAD

**Issue by DarkMatter513** [trustedsec/unicorn#135]
when doing python unicorn.py osx/x64/meterpreter/reverse_tcp <ip> <port> macro. 
error comes out as use proper format 00x or metasploit format and then prints info of msfvenom command to encode a windows reverse tcp. is it possible that i need to have unicorn in metasploit directory? since unicorn is not able to find the osx payload but is able to find windows payload when unicorn is installed in a folder in desktop.

**Comment by trustedsec** [comment]
This is windows only.
