### ISSUE TITLE
'str' object has no attribute 'decode'

### ISSUE THREAD

**Issue by arykiller** [trustedsec/unicorn#138]
Hey I'm having an error when i try to make a payload 
i use the command 
python unicorn.py windows/meterpreter/reverse_https 192.168.0.109 443
![VirtualBox_kali linux_28_03_2020_21_09_23](https://user-images.githubusercontent.com/36006767/77830428-63d1f480-7139-11ea-8809-cbf4bd738f23.png)

I'm using 
kali linux 2019.4 
unicorn version: 3.8.3
python version: 3.8
metasploit version: 5.0.83

**Comment by HackingDave** [comment]
Fixed in 3.8.6, thanks!
