### ISSUE TITLE
Meterpreter Session URI unescape is obsolete

### ISSUE THREAD

**Issue by fs0c1ety-sec** [trustedsec/unicorn#141]
Hi,

I'm having problems with unicor... i'm getting an URI unescape warning after the Meterpreter session opened and can only "exit -y" to stop it.

Unicorn version used:
Newest. 
Just did a git clone a few hours ago.

Payload:
windows/meterpreter/reverse_http
Lhost: 192.168.178.26
Lport:  11111

First i'm getting a problem even when i try to execute the obfuscated powershell payload on my Windows 10 x64 Pro Machine. It's not executing correctly. I have to turn off Windows Defender and execute the payload otherwise i won't get a session back.
But Windows Defender is not picking up the payload it's not detecting the powershell injection.

![ps_before_execute](https://user-images.githubusercontent.com/64715846/80896618-977fdb80-8cf0-11ea-8b7e-ad9774098760.png)
Running Powershell before executing the payload.
![ps_code](https://user-images.githubusercontent.com/64715846/80896635-c433f300-8cf0-11ea-8a51-5697483db60f.png)
Executing the Payload in Powershell.
![image](https://user-images.githubusercontent.com/64715846/80896650-df066780-8cf0-11ea-8ee9-06e001d541a5.png)
Started Handler and waiting for connections.
![ps_multiple](https://user-images.githubusercontent.com/64715846/80896660-f6ddeb80-8cf0-11ea-8569-2892ffb39a68.png)
After turning off Windows Defender the payload gets executed... but it opens multiple powershell instances. 
![image2](https://user-images.githubusercontent.com/64715846/80896669-15dc7d80-8cf1-11ea-96a1-5020bcfaf76b.png)
Getting Meterpreter Session opened with URI unescape warning...

Thank You in advance for any help!

**Comment by HackingDave** [comment]
What version of Metasploit are you using?

**Comment by fs0c1ety-sec** [comment]
My Metasploit version is 5.0.86

**Comment by HackingDave** [comment]
Tested on the latest version of Metasploit and Unicorn, it is working. Thanks for the report!
