### ISSUE TITLE
Powershell errors on execution

### ISSUE THREAD

**Issue by realagentwhite** [trustedsec/unicorn#144]
Powershell seems to have issues reading the payload. I've tried to fix the issue but nothing works.
Even decoding the payload seems to not work either.
Unicorn version: 3.9 (latest)
Windows OS: 10 (it's secure right ;) )
[powershell_attack.txt](https://github.com/trustedsec/unicorn/files/4630399/powershell_attack.txt)
[powershell_errors.txt](https://github.com/trustedsec/unicorn/files/4630400/powershell_errors.txt)

**Comment by HackingDave** [comment]
Fixed the connection back issue, it should work now.

**Comment by realagentwhite** [comment]
Works well! Gonna close it. Thanks @HackingDave !!
