### ISSUE TITLE
I am having issues getting my callbacks 

### ISSUE THREAD

**Issue by DorjM** [trustedsec/unicorn#146]
I am having issues getting my callbacks with recent deployment. However i got the message "[Error Code: -219]", still not get reverse connection.

I'm running it on 10.0.17134 N/A Build 17134
https://pastebin.com/XGs0L71S

Thanks for your help @HackingDave

**Comment by HackingDave** [comment]
I'll take a peek at this later today, looks like the update I did for the AMSI_BYPASS might be conflicting, maybe try turning AMSI_BYPASS to OFF and see if that corrects, it might not. I'll get a fix out though. Thanks for submitting it!

**Comment by HackingDave** [comment]
Just pushed a new version out in 3.12. This is fixed, thanks for the report and appreciate it!
