### ISSUE TITLE
the powershell script is detectable.

### ISSUE THREAD

**Issue by zisis912** [trustedsec/unicorn#154]
as you can see in the image, i ran the AMSI bypass powershell command, but it was detected. Literally the only antivirus that i have is windows defender. (The normal non-AMSI command didn't even work, it just closes powershell)
I am using windows/meterpreter/reverse_https i think.

I followed this guide to use it.
https://null-byte.wonderhowto.com/how-to/hacking-windows-10-create-undetectable-payload-part-1-bypassing-antivirus-software-0185055/
![image](https://user-images.githubusercontent.com/65046191/101091940-8b7b3580-35c1-11eb-94ea-23676dd567b4.png)

**Comment by thejoker3000** [comment]
You should watch this: https://www.youtube.com/watch?v=6G9DD6SkVqk
then you will know why this happens.
It is normal. If it is detected, don't freak out, it's normal, like I said.

**Comment by zisis912** [comment]
Isn't this entire project made to create undetectable payloads? Why would you need to rewrite the tool to make it create undetectable scripts

**Comment by zisis912** [comment]
also, i should mention that powershell also blocks scripts for thefatrat

**Comment by thejoker3000** [comment]
Watch the video I sent and you will understand better how the tool works (hopefully).
Also, you don't have to re-write the entire tool for it to work. 

Seriously, watch the YT video when you are bored or whatever. It will make better sense to you.

**Comment by zisis912** [comment]
i will watch the video tomorrow, but I just want to ask one more question.(maybe the video can answer it for me, but ill check it tomorrow) If you can rewrite a small portion of the tool to make it undetectable, and dave kenedy told trustedsec himself how to do it, why didnt trustedsec just make the change in the code and upload the change to github

**Comment by zisis912** [comment]
I watched the video, and im wondering which one of these ways should I use to make the script bypass amsi? Modify the base64 code, use that project by rasta, or use that guide to modify metasploit's payload.dll

**Comment by thejoker3000** [comment]
I suggest you join the discord server and ask in the #ask-help channel. https://discord.gg/trustedsec

**Comment by zisis912** [comment]
I asked, but it takes over a day for anyone to answer
