### ISSUE TITLE
Logical Error in Help Section

### ISSUE THREAD

**Issue by b0rne-ug** [trustedsec/unicorn#156]
Script always jumps to the help output as long as there are more than 2 arguments. 

This is because of the logical error below: 
https://github.com/trustedsec/unicorn/blob/22f94cc2786756d3f615abe1556a199605ecaf22/unicorn.py#L1230

I recommend it be changed to 

```        if len(sys.argv) > 2 and sys.argv[1] in help_options:```

**Comment by thejoker3000** [comment]
What is the command you are running? Can you share so I can check it? Because it shouldn't do that

**Comment by b0rne-ug** [comment]
when you run a command like `python unicorn.py muahahaha.ps1 macro 500` it goes straight to the help menu

**Comment by HackingDave** [comment]
Looks good, will be in the next release, thanks!
