### ISSUE TITLE
Macro detected by windows defender.

### ISSUE THREAD

**Issue by Viss** [trustedsec/unicorn#20]
Looks like the format of the macro is being picked up by windows defender.
It may be a good idea to poach the output format of empire's macro payload, since that still doesn't get detected :D

**Comment by trustedsec** [comment]
Hehe, I don't like snagging other peoples stuff.. I'll write a stub encoder for it.. Have plenty of space to play with. Should be done next couple days

**Comment by trustedsec** [comment]
Thanks for letting me know btw! Appreciate it.

Does it get snagged upon opening and enabling the macro or as soon as its downloaded?

**Comment by Viss** [comment]
windows 10, newish office install, defender pops when you try and open it.

I wager rearranging the payload and perhaps obfuscating the powershell.exe string will likely be enough, but I havent tried myself

**Comment by beethical** [comment]
Same problem here!
Today, I checked the latest Macro created via unicorn (and veil) through every available Antivirus, and some of them detected the Macro as a Trojan,even before opening the document ! :)
The screenshot below shows the results:

![photo_2016-06-30_13-43-17](https://cloud.githubusercontent.com/assets/19576824/16483354/476f719c-3ec9-11e6-80ef-c6c4bb1bd70a.jpg)

**Comment by trustedsec** [comment]
tested macro injection and normal ps1 - looks to get around windows defender with the update I just pushed out - let me know your experience but closing this for now. Will re-open if that differs. Thanks for the report!

**Comment by Viss** [comment]
THANK YOU SIR <3

**Comment by Viss** [comment]
I will test.
