### ISSUE TITLE
unicorn detection

### ISSUE THREAD

**Issue by hostbob** [trustedsec/unicorn#23]
Nice project keep up the good work man.

I test this Macro Attack against Kaspersky and NOD32 but it was detected in memory and closed due it uses powershell to execute another powershell. do you think there is a way this can be bypasseed in some ways?

Thanks

**Comment by trustedsec** [comment]
Macros are tough because they look for anything launching from here. It's always a cat and mouse game with AV. What you can do is use Invoke-Obfuscation and base64 it to a one liner and should get around it.

If I get some time next week, I'll go through and write better obfuscation and test.

**Comment by hostbob** [comment]
how do i use invoke-obfuscation and base64 to a one liner?

Thanks for your response

**Comment by drale2k** [comment]
Bump, can you elaborate on this? Also running into Kaspersky because macro tries to run powershell
