### ISSUE TITLE
error sintaxis in macro attack

### ISSUE THREAD

**Issue by gearcapitan** [trustedsec/unicorn#28]
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/22410146/b6c9d59a-e659-11e6-8333-49fd9eb6035e.png)

**Comment by lystena** [comment]
It doesn't escape the double quotes in the string and seemed to have some issues with single quotes. A quick and dirty way of fixing it is to create two variables aka:
y = "\<encoded base64 string\>" _
& "..."
x = "powershell -w 1 -C 'sv j -;sv y ec;sv wz ((gv j).value.toString()+(gv y).value.toString());powershell (gv wz).value.toString()" + y +"'"

**Comment by gearcapitan** [comment]
I still did not work
![1](https://cloud.githubusercontent.com/assets/13740942/23176302/17424cf6-f828-11e6-9427-5251edeb1358.png)
![2](https://cloud.githubusercontent.com/assets/13740942/23176309/19750392-f828-11e6-8e6e-07cd29b62830.png)


error of sintaxis

**Comment by gearcapitan** [comment]
![1](https://cloud.githubusercontent.com/assets/13740942/23181077/2ac4f786-f839-11e6-97f7-0e79ee30ffe1.png)
![2](https://cloud.githubusercontent.com/assets/13740942/23181078/2ac71f70-f839-11e6-9a8e-5c6e27f3abb4.png)
![3](https://cloud.githubusercontent.com/assets/13740942/23181079/2acc7c86-f839-11e6-97a7-ce6f798eb355.png)

OK, AS IS THE FILE READY, BUT THE CONNECTION IS NOT ESTABLISHED, POWERSHELL ONLY RUNS 1 SECOND AND CLOSES, IT IS NOT A NETWORK CASE, AT THESE HEIGHTS IT WILL BE THAT NOT THE PROBLEM, AS I SCRIPT ALREADY IF YOU ARE EVIL, IT IS EVIL EYE AND THEREFORE IT DOES NOT CONNECT

**Comment by byt3bl33d3r** [comment]
![axtzzik](https://cloud.githubusercontent.com/assets/5151193/23182987/af388e26-f837-11e6-84a4-3b7fd326d982.gif)

**Comment by trustedsec** [comment]
Looks like how things are being parsed out with single quotes and double quotes, I'll work on this a bit and see if I can't get it fixed. @byt3bl33d3r - that is almost hypnotic.

**Comment by trustedsec** [comment]
That was a m'fer to fix. It's now fixed and released. Thanks for the report.
