### ISSUE TITLE
FAil antivirus detected!

### ISSUE THREAD

**Issue by gearcapitan** [trustedsec/unicorn#29]
Thanks even so for the script, it is a pity that this detected by so many common antivirus but is really appreciated its dedication, some way of obfuscating the code so that it is not detected?

http://nodistribute.com/result/BStaMqvhjY7uFODniRJQxN
![sin titulo](https://cloud.githubusercontent.com/assets/13740942/23198220/9009ed20-f88b-11e6-904c-5dbeaf468a75.png)

**Comment by trustedsec** [comment]
Looks like it is simply flagging on that its macro enabled - not that its on the code. Change some of the wording and critical microsoft error comments and you'll be fine.

**Comment by trustedsec** [comment]
Give it a shot now, just rewrote the entire obfuscation piece :)

**Comment by gearcapitan** [comment]
Are they really going to obfuscate the code ?, until now I only have problems with kasperksy and avast that are the only ones that detect me the macro with what it achieves

**Comment by trustedsec** [comment]
I'm saying the new version has obfuscation built into it - doesn't get snagged by either now and should be much harder in the future.

**Comment by gearcapitan** [comment]
Ok thanks, then wait for the new version
