### ISSUE TITLE
Word 2016 : Powershell Macro not launched automatically

### ISSUE THREAD

**Issue by craigdods** [trustedsec/unicorn#35]
Hello,

Big fan, just ran into an issue with a relatively small powershell macro. When opening Word 2016, I'd expect, after "Enabling Content", that the Macro should launch automatically... but it does not. I can only launch it by navigating to "View -> Macro -> Run -> Auto_Open", and then the payload is executed successfully. 

Macro was created with the "macro 500" switch and seems to be fully functional as seen when executed manually.

Thoughts? What can I do to debug this?

**Comment by craigdods** [comment]
Figured this out and it's ridiculous (I kid you not).

Word 2016 doesn't recognize Auto_Open as a valid option. They substituted it for AutoOpen...

Macro Title needs to be AutoOpen now and the VBA is:
Sub AutoOpen()

**Comment by craigdods** [comment]
I've added a commit here for your review. It's just comments and can be made cleaner in the code itself, let me know if you want some help.

Thanks again for the fantastic tool : )

Commit: #36b1127 #

**Comment by trustedsec** [comment]
For excel its Auto_Open() for Word it's AutoOpen() lol. Not sure why they are different :) Also, didn't see the commit or PR.

**Comment by craigdods** [comment]
Hah, that's just lovely...

Direct link is here (I had to fork it of course):

https://github.com/craigdods/unicorn/commit/36b1127c6c61f7bce91faa0d7db3d1bc72a93f16

**Comment by trustedsec** [comment]
Thanks, adding into next release :) Appreciate it!
