### ISSUE TITLE
need help

### ISSUE THREAD

**Issue by wermaxta** [trustedsec/unicorn#38]
Hi i have problem with new version of unicorn 
My OS is Kali linux 
Linux kali 4.9.0-kali3-amd64 #1 SMP Debian 4.9.16-1kali1 (2017-03-24) x86_64 GNU/Linux
when i type python unicorn.py i got this message
File "unicorn.py", line 550
    <<<<<<< HEAD
    ^
IndentationError: expected an indented block
Thank You :)))))

**Comment by trustedsec** [comment]
Looks like you downloaded a bad version of unicorn? There shouldn't be a HEAD inside the source.  I would re-check out Unicorn to the latest version.

**Comment by trustedsec** [comment]
I was actually wrong on this - there was a merge issue and caused that to be thrown in. I've since fixed. Thanks for reporting :)

**Comment by wermaxta** [comment]
Now it OK 
Thank You :)
