### ISSUE TITLE
Word 2016

### ISSUE THREAD

**Issue by berentw** [trustedsec/unicorn#40]
I have been trying to use this today with Word 2016 (and Excel) without any success. I can use it with just powershell via commandline, session loads fine. But with Word (freshly installed earlier in the week in a fresh install of  Win10) I get nothing. Looking at traffic, nothing comes out of machine after I open the Word file at all. I can't see any error or feedback that is any different to expectations from videos online. It does the popup saying older version of word. Just doesn't seem to send the payload to powershell.

**Comment by trustedsec** [comment]
Change Auto_Open to AutoOpen. :)

**Comment by berentw** [comment]
Yes I did that. Now about 10-15 times..

**Comment by berentw** [comment]
Tried again, still failed for Word but worked for pasting into c.prompt (different generations of the code obviously, and yes I made it AutoOpen as I have a bunch of other times). I have them both Kali and Win10 in vbox.
