### ISSUE TITLE
macro not connect

### ISSUE THREAD

**Issue by gearcapitan** [trustedsec/unicorn#42]
macro attack in version 2.7.2 dont connect, but in version 2.6 connect with out problems

**Comment by gearcapitan** [comment]
![kali linux-2017-04-13-22-02-13](https://cloud.githubusercontent.com/assets/13740942/25031784/ecff648e-2094-11e7-8c2e-256e89e0fd0a.png)

**Comment by drale2k** [comment]
Same issue here, 2.6 works fine but 2.7.2 doesn't

**Comment by drale2k** [comment]
Update: It happened from 2.6 to 2.7. I tested reverse_tcp and https, both don't work in 2.7+

**Comment by bgxdoc** [comment]
Same issue here, 2.7 macro code doesn't work. i tried editing macro code but no luck so far.

**Comment by trustedsec** [comment]
I'll take a stab at this shortly - sorry on the delay. DerbyCon has been kicking my ass lol.

**Comment by trustedsec** [comment]
Figured out the issue, it's going to be a few hours before I can fix it... Complex in how I generate the obfuscation.

**Comment by trustedsec** [comment]
Okay, I have fixed this in 2.7.3 - sorry it took so long folks. Phew.
