### ISSUE TITLE
download_exec for HTA

### ISSUE THREAD

**Issue by hostbob** [trustedsec/unicorn#43]
can you try implement download_exec for HTA file? the reverse is kinda suck sometimes and would have been really good if can use download_exec command

Shares

**Comment by hostbob** [comment]
the macro is not executing when opening, do you notice this?

**Comment by trustedsec** [comment]
Fixed in 2.7.3, thanks for the report!

**Comment by hostbob** [comment]
The macro is detected by ESET on runtime, dont know if this might also happen with some other AV which uses ESET technic to detect virus.

**Comment by trustedsec** [comment]
Then change it around to not get detected :)

**Comment by hostbob** [comment]
i can't mess with the script code, maybe pointing out a way might be helpful as there is no other syntax included in the README, just how to build file
