### ISSUE TITLE
We have a problem here

### ISSUE THREAD

**Issue by themonio** [trustedsec/unicorn#47]
Well, bypass properly the AV using my own obfuscation and using the system memory.

The problem now is that, when I'm in the meterpreter and I try to migrate or open the shell, this action is suspicious and is blocked by the "victim" AV.

So, I can start the session shell, but once I'm on the session, each action or movement from meterpreter is caught by mr kspky

Any hint? thanks

**Comment by basketas** [comment]
I also managed to get a session with meterpreter, and as soon as session is established and metasploit starts sending stageless payload, kasper detects it.. 
It's a problem with meterpreter, not unicorn.. Even if you set these:
set EnableStageEncoding true
set Encoder x86/shikata_ga_nai:12
... I can't figure out why... If my handler is not listening, then kasper won't detect it....

**Comment by themonio** [comment]
I'm not completely sure, but in my opinion this is not depending on meterpreter really. I think that the AV detect suspicious internal commands to powerShell and it blocks directly. What do you think.

**Comment by themonio** [comment]
Hey @basketas I tried to move the process to another process before connecting the handler and it detects on handler start and now with another process (not powershell) so you are right. Seems that the av detects the meterpreter connection. Did you try this? https://github.com/rapid7/metasploit-framework/wiki/Meterpreter-Paranoid-Mode

**Comment by themonio** [comment]
Nothing... With Paranoid Mode, kaspersky still caught the connection :/

**Comment by trustedsec** [comment]
Then write it so it gets around, this is a framework, not a cat and mouse game :P
