### ISSUE TITLE
the help file sample usage is basically unreadable

### ISSUE THREAD

**Issue by carnal0wnage** [trustedsec/unicorn#49]
fix formatting plz

**Comment by trustedsec** [comment]
Whats wrong with the formatting?

**Comment by carnal0wnage** [comment]
<img width="1083" alt="screen shot 2017-06-14 at 8 28 53 am" src="https://user-images.githubusercontent.com/735360/27132105-8dd4dbca-50db-11e7-96f8-e69dcab453ea.png">

**Comment by carnal0wnage** [comment]
probably just needs to be marked as code in the markdown

**Comment by trustedsec** [comment]
Ahhh, okay thanks. Will fix :) xoxo

**Comment by trustedsec** [comment]
Fixed, thanks :)
