### ISSUE TITLE
kaspersky detected

### ISSUE THREAD

**Issue by gearcapitan** [trustedsec/unicorn#53]
![captura de pantalla 64](https://user-images.githubusercontent.com/13740942/31034322-3155a15c-a529-11e7-8c82-923a50407106.png)

**Comment by basketas** [comment]
The 2nd stage of meterpreter is detected and there is nothing you can do about except rewriting meterpreter.

**Comment by trustedsec** [comment]
On the reverse HTTPS - you can always use legitimate certificates and certificate pinning, usually gets around that.
