### ISSUE TITLE
dont return session in kali.

### ISSUE THREAD

**Issue by johnjohny1990** [trustedsec/unicorn#55]
hi
I generate payload with unicorn in kali 2016.when i run pwershell.bat dont give any access to me .dont return session in kali.
i think your code dont work.
please help me .
thanks

**Comment by trustedsec** [comment]
Please ensure you are running the latest version of Metasploit, the kali 2016 is super old.... Code is working - tested recently.

**Comment by johnjohny1990** [comment]
yes.thank but dont fud
