### ISSUE TITLE
when open Word DDE nothing happend in handler  ?

### ISSUE THREAD

**Issue by mateo24xx** [trustedsec/unicorn#58]
linux 2017

i see port 443 open in canyouseeme..
![capture dcdpng](https://user-images.githubusercontent.com/24534204/32470376-d0fc76bc-c357-11e7-9dbb-98ea880d2126.PNG)

**Comment by trustedsec** [comment]
Length of DDE is an issue apparently, I've rewritten to use obfuscated IEX, will need to host ps1 file somewhere to execute.
