### ISSUE TITLE
reverse_https payload above command line limit

### ISSUE THREAD

**Issue by Bry-fi** [trustedsec/unicorn#63]
The payload will refuse to generate a reverse_https payload but other payloads will turn out fine.

**Comment by gearcapitan** [comment]
![imagen](https://user-images.githubusercontent.com/13740942/34390621-90eb397e-eb06-11e7-99be-d15c276d42c1.png)
 I have the same problem

**Comment by Bry-fi** [comment]
I think rapid7 changed the reverse_https code.

**Comment by elusive94** [comment]
Yes, rapid7 has changed the "CachedSize"  in all payloads, and now reverse_https above command line limit. I tried with metasploit 4.16.18 it's works.

**Comment by trustedsec** [comment]
Bleah. Let me see what I can do.

**Comment by trustedsec** [comment]
Okay fixed with latest Metasploit version.

**Comment by trustedsec** [comment]
I mean in the latest version of Unicorn with the latest version of Metasploit :)
