### ISSUE TITLE
DDE meterpreter/reverse_https payload consistently exceeds command line limit

### ISSUE THREAD

**Issue by strikeoncmputrz** [trustedsec/unicorn#64]
First, thank you Dave for this awesome tool! 

I've been trying to generate a DDE meterpreter/reverse_https payload but I cannot due to the payload exceeding the command line limit. 

I have tried with various IPs to include the example that unicorn provides: python unicorn.py windows/meterpreter/reverse_https 192.168.5.5 443 dde

Unicorn provides this warning: [!] WARNING. WARNING. Length of the payload is above command line limit length of 8191. Recommend trying to generate again or the line will be cut off.
Press {return} to continue.

I am using the latest version of unicorn via this repo.   Thanks again!

**Comment by trustedsec** [comment]
Yeah, looks to be an issue with R7 updating the payload size, I'll see what I can do here.

**Comment by strikeoncmputrz** [comment]
Thanks for the reply! I eventually settled for good old reverse_tcp and got my shell that way.

**Comment by trustedsec** [comment]
Fixed in the latest version, and glad to hear it! Just pushed a new version out that fixes the size length :) Thanks for the report!
