### ISSUE TITLE
[!] Cobalt Strike file either not formatted properly or not the C#/CS format.

### ISSUE THREAD

**Issue by CorpOfHack** [trustedsec/unicorn#67]
Syntax of **cobalt_strike_payload.cs** generated as C#/CS payload looks like to this:
`/* length: 527 bytes */
byte buf[] = new byte[527]`

But unicorn.py check this file with this string:
`/* length: 527 bytes */
byte[] buf = new byte[527]`

If we are not change this value we will got an error:
**[!] Cobalt Strike file either not formatted properly or not the C#/CS format.**

**Comment by trustedsec** [comment]
I'm not sure if you are using an older version or what not - the latest CS generates the template like below and parses correctly:

/* length: 836 bytes */
byte[] buf = new byte[836]

**Comment by gearcapitan** [comment]
I have the same  error,
my version of cobaltstrike is 3.8 
![kali_linux-2018-04-04-19-29-47](https://user-images.githubusercontent.com/13740942/38341531-af810474-383e-11e8-94ca-4dfe04268c0b.png)
![kali_linux-2018-04-04-19-29-55](https://user-images.githubusercontent.com/13740942/38341532-af9b4596-383e-11e8-8bce-e1afc5457ed7.png)

**Comment by trustedsec** [comment]
Really weird, mine exports the other way. I've added this as an additional check and will be in 3.1.. Working on a backwards compatibility with windows 7 thing now, soon as thats fixed, I'll push both variations. Thanks!
