### ISSUE TITLE
powershell.exe has moved to virus chest

### ISSUE THREAD

**Issue by hackdrug** [trustedsec/unicorn#68]
after executing the payload file, suddenly antivrus popup and say powershell.exe has moved to virus chest. no sessions start in metasploit. any idea ?

**Comment by trustedsec** [comment]
Which antivirus?

**Comment by hackdrug** [comment]
avast

**Comment by salamohamad** [comment]
Kaspersky does the something as well. Of course. Antivirus is very good at finding weird behaviour. Which regardless, any macro running an UN-affiliated and UN-opened process will automatically be categorised as Virus and will be removed form the file itself.

**Comment by trustedsec** [comment]
Anti-virus is not good at finding weird behavior in my experience. It's a matter of if someone wrote a signature and if your signature evades. Behavior is usually less common. I've pushed an update that fixes this.
