### ISSUE TITLE
Embedded persistence

### ISSUE THREAD

**Issue by ronnieflip** [trustedsec/unicorn#7]
Hi, i was wondering if you have thought of a way to initially include persistence during the generation of the payload.
Cheers

**Comment by trustedsec** [comment]
Hey Ronnie - the main point of it is to be memory resident and evade any type of persistence hooks. You can use run persistence or use other methods for persistence but its easy to typically detect. I would advise against unless you are testing things. This isn't a feature I think I would be willing to add but its definitely something I'll contemplate in the future!
