### ISSUE TITLE
Access is Denied

### ISSUE THREAD

**Issue by corrupt-technology** [trustedsec/unicorn#70]
when executing under a local administrator account on Windows 8.1
(ESET installed) 

execution method is copy/paste powershell command from the file to a local cmd.exe spawned from psexec with metasploit.

**Comment by trustedsec** [comment]
Is this powershell generated by Unicorn? It looks like you are using psexec with Metasploit - access is denied is usually an indicator of permissions - with Windows 8 and above, only the 500 RID account (administrator) has the ability to do PSEXEC on admin$ shares.
