### ISSUE TITLE
issue with powershell payload

### ISSUE THREAD

**Issue by Exotic-Algorithms** [trustedsec/unicorn#72]
after running it on windows 10 i get the error "this app cannot run on your pc". This is strange because the other times iv ran it it worked just fine.

**Comment by orphicone** [comment]
Did you recently update to Windows 10 1803 (recent upgrade)? Had similar lab issues post update.

**Comment by trustedsec** [comment]
Just tested on 1803, working good... I know there was some issues with the cobalt strike and meterpreter payloads, they have been fixed due to some changes in PowerShell
