### ISSUE TITLE
[HELP] excecuted the payload command in an elevated cmd and stil doesnt work

### ISSUE THREAD

**Issue by clancrate** [trustedsec/unicorn#80]
I'm having trouble establishing a meterpreter connection on my extra lappy. I intentionally disabled the antivirus and windows defender and it still doesn't work. the code runs for a sec and closes. target is not a fully updated windows 10 32bit computer

heres the payload: https://pastebin.com/iwnm0j47
and heres the unicorn.rc file: https://pastebin.com/HpRMZrYW

any help would be appreciated :)

**Comment by trustedsec** [comment]
Unicorn is for 64 bit platforms, I removed the 32 bit compatibility since we don't see that out in the wild anymore.
