### ISSUE TITLE
Do not get session

### ISSUE THREAD

**Issue by PinkPantherX** [trustedsec/unicorn#85]
After update, powershell script is undetectable but doesnt get session. I've tried multiple attacks, but no session. At hte end I've copied script into cmd and still get no session. I doublechecked if all parameters are Ok.

**Comment by trustedsec** [comment]
Which update and 32 or 64 bit platform ?

**Comment by PinkPantherX** [comment]
I've reinstalled Unicorn on my Kali linux and targeted comp. is Win10 64bit. Windows Defender is on and expired Eset trial version.

**Comment by trustedsec** [comment]
What version of unicorn ? :-)

**Comment by trustedsec** [comment]
I did do a bug fix - should solve and tested on the latest.
