### ISSUE TITLE
Supported Windows / Office Versions

### ISSUE THREAD

**Issue by drale2k** [trustedsec/unicorn#9]
Sorry for opening an issue for this but i don't know where else to ask.

I have tested unicorn successfully under Windows 7 & Office 2016. Any idea what other Windows / Office versions are supported?

**Comment by trustedsec** [comment]
No problem and appreciate posting on here - I haven't run into any specific versions of Windows that it isn't compatible with as long as it has PowerShell.. so it should be Windows Vista and above..
