### ISSUE TITLE
Macro download&exec

### ISSUE THREAD

**Issue by moaeddy** [trustedsec/unicorn#93]
unicorn do not support download & exec macro anymore?

**Comment by trustedsec** [comment]
This was a bug, just pushed an update that fixes it. Thanks for the report!

**Comment by moaeddy** [comment]
but you didn't include how to build macro using download & exec function like before?

**Comment by trustedsec** [comment]
? use download/exec with macro at the end. It's the same.

**Comment by moaeddy** [comment]
updated, but got too many lines CONTINUATIONS when inserting into office.

**Comment by trustedsec** [comment]
Turn off the AMSI bypass on it then, or you can chunk up the payload to more variables. Edit unicorn.py and turn AMSI_BYPASS to OFF. It also depends on the version of Office you are doing for the line continuation issue. It's not a unicorn problem unfortunately.
